import { useState } from "react";
import { ArrowRight, BookOpen, Check, ChevronRight, FileText, Leaf, LockKeyhole, Mail, MapPinned, ShieldCheck, Sprout, Trees, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";

const logo = "/manus-storage/treeway-forest-logo_5b4a11f0.png";

type Article = { category: string; title: string; excerpt: string; read: string; accent: string; body: string };
const articles: Article[] = [
  { category: "Gestão de talhões", title: "O que muda quando cada talhão tem uma história própria", excerpt: "Como organizar espécie, ciclo, área, mapa e operação para decidir com contexto.", read: "6 min de leitura", accent: "bg-[#e6f0e5]", body: "Uma floresta não é uma linha única. Cada talhão carrega espécie, idade, acesso, manejo, risco e potencial. Quando essas informações ficam conectadas, o planejamento deixa de depender de planilhas soltas e passa a acompanhar a realidade do campo." },
  { category: "Controle financeiro", title: "Caixa realizado: a diferença entre vender e receber", excerpt: "Entenda por que receita nominal e dinheiro em caixa precisam aparecer separados.", read: "5 min de leitura", accent: "bg-[#fff0e6]", body: "Uma venda pode estar contratada, faturada ou parcialmente recebida. A gestão segura separa esses momentos e mostra o que efetivamente entrou e saiu, evitando que uma previsão seja confundida com caixa disponível." },
  { category: "Operação de campo", title: "Tickets, fotos e ocorrências: o diário que protege a operação", excerpt: "Um método simples para registrar o que aconteceu enquanto a equipe ainda está no campo.", read: "7 min de leitura", accent: "bg-[#eeece2]", body: "O registro de campo ganha valor quando está associado ao talhão, ao ticket, à data e à evidência visual. Essa sequência cria contexto para conferências, vistorias e decisões posteriores." },
];

function Brand() { return <a href="/" className="flex items-center gap-3 text-[#123b2c]"><img src={logo} className="h-11 w-11 rounded-2xl bg-[#123b2c] p-2 shadow-lg" alt="Treeway Forest"/><span className="text-xl font-semibold tracking-[-.04em]">Treeway<span className="text-[#e16d32]">.</span></span></a>; }

export default function PublicContentPage() {
  const [selected, setSelected] = useState<Article | null>(null);
  const [unlocked, setUnlocked] = useState(false);
  const [sent, setSent] = useState(false);
  const [error, setError] = useState("");
  const captureLead = trpc.content.captureLead.useMutation({ onSuccess: () => { setSent(true); setUnlocked(true); setError(""); }, onError: (err) => setError(err.message || "Não foi possível concluir o cadastro agora.") });
  return <div className="min-h-screen bg-[#f7f8f3] text-[#123b2c]">
    <header className="border-b border-[#dce5db] bg-[#f7f8f3]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Brand/><nav className="hidden items-center gap-6 text-sm font-medium text-[#6a7d70] md:flex"><a href="/#solucao" className="hover:text-[#e16d32]">Solução</a><a href="/conteudos" className="text-[#e16d32]">Conteúdos</a><a href="/comprar" className="hover:text-[#e16d32]">Planos</a></nav><a href="/" className="text-sm font-semibold text-[#6a7d70] hover:text-[#e16d32]">Voltar</a></div></header>
    <main>
      <section className="relative overflow-hidden bg-[#123b2c] px-5 py-20 text-white lg:py-28"><div className="absolute -right-28 -top-28 h-96 w-96 rounded-full border border-[#f08a4e]/20"/><div className="absolute right-10 top-10 h-52 w-52 rounded-full border border-[#f08a4e]/15"/><div className="relative mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.24em] text-[#f08a4e]">Treeway field notes</p><h1 className="mt-5 text-5xl font-semibold leading-[.94] tracking-[-.06em] sm:text-7xl">Ideias para cuidar melhor da operação.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">Conteúdos curtos, práticos e feitos para quem precisa transformar informação de campo em decisão.</p></div><div className="mt-10 flex flex-wrap gap-3 text-xs font-mono uppercase tracking-[.16em] text-white/50"><span>Pinus</span><span>·</span><span>Eucalipto</span><span>·</span><span>Talhões</span><span>·</span><span>Caixa</span></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#e16d32]">Conteúdos em destaque</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.05em]">Conhecimento que acompanha o campo.</h2></div><p className="max-w-md text-sm leading-6 text-[#718177]">Leia a prévia gratuitamente. Para continuar, deixe um contato e escolha se deseja receber novidades.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{articles.map(article=><Card key={article.title} className="group flex h-full flex-col border-[#dce5db] bg-white transition duration-300 hover:-translate-y-1 hover:shadow-[0_22px_50px_-35px_rgba(18,59,44,.7)]"><CardHeader><div className={`flex h-12 w-12 items-center justify-center rounded-2xl ${article.accent}`}><BookOpen className="h-5 w-5 text-[#2e6b49]"/></div><p className="mt-6 text-[10px] font-bold uppercase tracking-[.18em] text-[#e16d32]">{article.category}</p><CardTitle className="mt-2 text-2xl leading-tight tracking-[-.03em]">{article.title}</CardTitle></CardHeader><CardContent className="flex flex-1 flex-col"><p className="text-sm leading-6 text-[#718177]">{article.excerpt}</p><div className="mt-auto flex items-center justify-between pt-8 text-xs text-[#8a9a8d]"><span>{article.read}</span><button className="font-semibold text-[#e16d32] transition group-hover:translate-x-1" onClick={()=>setSelected(article)}>Ler matéria <ArrowRight className="ml-1 inline h-3.5 w-3.5"/></button></div></CardContent></Card>)}</div></section>
      {selected && <section className="border-y border-[#dce5db] bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-[1fr_380px] lg:px-8"><div><button onClick={()=>setSelected(null)} className="text-xs font-semibold text-[#e16d32]">← Voltar aos conteúdos</button><p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-[#e16d32]">{selected.category}</p><h2 className="mt-3 max-w-3xl text-4xl font-semibold leading-tight tracking-[-.05em]">{selected.title}</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-[#64776c]">{selected.body}</p>{unlocked && <div className="mt-8 max-w-2xl rounded-2xl bg-[#e8f1e8] p-6 text-sm leading-7 text-[#315d43]"><strong>Conteúdo liberado.</strong> Continue explorando a Treeway e transforme este princípio em uma rotina de operação dentro da plataforma.</div>}</div>{!unlocked && <Card className="h-fit border-[#dce5db] bg-[#f8faf5]"><CardHeader><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#123b2c] text-white"><LockKeyhole className="h-4 w-4"/></div><CardTitle className="mt-4 text-xl">Continue a leitura</CardTitle><p className="text-sm leading-6 text-[#718177]">Receba o conteúdo completo e novidades práticas da Treeway.</p></CardHeader><CardContent>{sent?<div className="rounded-xl bg-[#e8f1e8] p-4 text-sm leading-6 text-[#315d43]">Cadastro recebido. O conteúdo completo foi liberado para esta leitura.</div>:<form className="space-y-4" onSubmit={e=>{e.preventDefault();const form = new FormData(e.currentTarget);captureLead.mutate({name:String(form.get("name")||""),email:String(form.get("email")||""),whatsapp:String(form.get("whatsapp")||"")||null,contentUpdatesConsent:true,commercialContactConsent:form.get("commercial") === "on",source:`conteudos:${selected.category}`})}}>
<div><Label htmlFor="content-name">Nome</Label><Input id="content-name" name="name" required placeholder="Como podemos chamar você?"/></div><div><Label htmlFor="content-email">E-mail</Label><Input id="content-email" name="email" type="email" required placeholder="voce@empresa.com"/></div><div><Label htmlFor="content-whatsapp">WhatsApp <span className="font-normal text-[#8a9a8d]">(opcional)</span></Label><Input id="content-whatsapp" name="whatsapp" placeholder="(00) 00000-0000"/></div><label className="flex gap-3 text-xs leading-5 text-[#718177]"><input type="checkbox" name="updates" required className="mt-1 accent-[#e16d32]"/>Aceito receber atualizações e conteúdos exclusivos da Treeway. Posso cancelar quando quiser.</label><label className="flex gap-3 text-xs leading-5 text-[#718177]"><input type="checkbox" name="commercial" className="mt-1 accent-[#e16d32]"/>Aceito receber contato sobre a plataforma e seus planos.</label>{error && <p role="alert" className="text-xs font-medium text-red-700">{error}</p>}<Button disabled={captureLead.isPending} className="w-full bg-[#e16d32] text-white hover:bg-[#c95722]">{captureLead.isPending ? "Enviando…" : "Liberar leitura"} <ArrowRight className="ml-2 h-4 w-4"/></Button><p className="text-[10px] leading-4 text-[#8a9a8d]">Usaremos os dados somente conforme as opções escolhidas. Não compartilhamos seus contatos como parte desta experiência.</p></form>}</CardContent></Card>}</div></section>}
      <section className="bg-[#f0eee5] px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#e16d32]">Nossa história</p><h2 className="mt-4 text-4xl font-semibold leading-tight tracking-[-.05em]">Uma ideia que nasceu perto da operação.</h2><p className="mt-6 text-lg leading-8 text-[#526c5c]">A Treeway surgiu ao perceber que a gestão florestal precisava de um caminho mais simples entre o que acontece no campo e o que precisa ser decidido no escritório.</p><p className="mt-5 text-sm leading-7 text-[#6e7f73]">Começamos com uma pergunta prática: como reunir talhões, tickets, contratos, vistorias e caixa em uma visão que faça sentido para quem vive a rotina? A plataforma continua sendo construída com esse princípio: clareza antes de complexidade, registro antes de memória e contexto antes de pressa.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-white p-6"><Sprout className="h-5 w-5 text-[#e16d32]"/><h3 className="mt-5 font-semibold">Feita para a rotina real</h3><p className="mt-2 text-sm leading-6 text-[#718177]">A linguagem e os fluxos partem de situações concretas de manejo e operação.</p></div><div className="rounded-2xl bg-[#123b2c] p-6 text-white"><ShieldCheck className="h-5 w-5 text-[#f08a4e]"/><h3 className="mt-5 font-semibold">Transparência por design</h3><p className="mt-2 text-sm leading-6 text-white/60">O que é exemplo, previsão, pendência ou dado realizado aparece separado.</p></div><div className="rounded-2xl bg-white p-6 sm:col-span-2"><Trees className="h-5 w-5 text-[#2e6b49]"/><h3 className="mt-5 font-semibold">Um caminho que pode crescer com você</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-[#718177]">A Treeway organiza o presente e cria uma base para evoluir processos sem perder a história de cada área.</p></div></div></div></section>
      <section className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl rounded-[2rem] bg-[#123b2c] p-8 text-white sm:p-12"><div className="grid gap-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#f08a4e]">Pronto para ver na prática?</p><h2 className="mt-4 max-w-2xl text-4xl font-semibold tracking-[-.05em]">Conheça a plataforma por dentro.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-white/60">Entre para usar seus próprios dados ou veja o Tutorial com exemplos demonstrativos.</p></div><div className="flex flex-col gap-3 sm:flex-row"><a href="/tutorial" className="inline-flex h-12 items-center justify-center rounded-md border border-white/20 px-5 text-sm font-semibold text-white hover:bg-white/10">Ver Tutorial <ArrowRight className="ml-2 h-4 w-4"/></a><a href="/comprar" className="inline-flex h-12 items-center justify-center rounded-md bg-[#e16d32] px-5 text-sm font-semibold text-white hover:bg-[#c95722]">Conhecer o plano <ArrowRight className="ml-2 h-4 w-4"/></a></div></div></div></section>
    </main><footer className="border-t border-[#dce5db] px-5 py-8 text-center text-xs text-[#819087]">Treeway Forest · Conteúdos para decisões melhores no campo</footer>
  </div>;
}
