import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowRight, BarChart3, CheckCircle2, FileText, MapPinned, ReceiptText, ShieldCheck, Sparkles, TicketCheck, Trees, WalletCards } from "lucide-react";
import { useLocation } from "wouter";

const example = "EXEMPLO DEMONSTRATIVO";

function MiniChrome({ children }: { children: React.ReactNode }) {
  return <div className="overflow-hidden rounded-2xl border border-[#dce7dc] bg-[#fbfcf8] shadow-[0_18px_55px_-35px_rgba(18,59,44,.55)]"><div className="flex items-center gap-1.5 border-b border-[#e4ece3] bg-white px-4 py-3"><span className="h-2 w-2 rounded-full bg-[#e16d32]"/><span className="h-2 w-2 rounded-full bg-[#c5d1c5]"/><span className="h-2 w-2 rounded-full bg-[#c5d1c5]"/><span className="ml-auto rounded-full bg-[#edf3eb] px-2 py-1 font-mono text-[9px] text-[#6b806f]">treeway / demo</span></div>{children}</div>;
}

export default function TutorialPage() {
  const [, setLocation] = useLocation();
  return <div className="mx-auto max-w-6xl space-y-10">
    <section className="relative overflow-hidden rounded-[2rem] bg-[#123b2c] px-6 py-10 text-white shadow-[0_25px_70px_-35px_rgba(18,59,44,.8)] sm:px-10 lg:py-14"><div className="absolute -right-20 -top-28 h-72 w-72 rounded-full border border-[#f08a4e]/30 opacity-60"/><div className="absolute -right-8 -top-16 h-52 w-52 rounded-full border border-[#f08a4e]/20 opacity-60"/><div className="relative max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.18em] text-[#f5b085]"><Sparkles className="h-3.5 w-3.5"/> Guia rápido Treeway</div><h1 className="mt-5 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">Do mapa ao caixa, <span className="text-[#f08a4e]">sem perder o caminho.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/70">Este tutorial mostra, em poucos passos, como a Treeway organiza uma operação florestal. Os dados exibidos abaixo são fictícios e servem apenas para demonstração.</p><div className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[#e16d32]/15 px-3 py-2 text-xs font-semibold text-[#ffd0b3]"><ShieldCheck className="h-4 w-4"/> {example} · não é dado operacional</div></div></section>
    <section className="grid gap-5 lg:grid-cols-3">{[[MapPinned,"1. Desenhe o território","Cadastre a propriedade, divida os talhões e identifique pinus ou eucalipto. O mapa vira o ponto de partida de cada decisão."],[TicketCheck,"2. Registre o campo","Lance tickets, fotos, tonelagem, destino e ocorrências no momento em que a operação acontece."],[BarChart3,"3. Acompanhe o resultado","Cruze produção, contratos, despesas e caixa para saber o que precisa de atenção agora."]].map(([Icon,title,desc])=><Card key={title as string} className="border-[#dce7dc] bg-white shadow-[0_16px_45px_-36px_rgba(18,59,44,.7)]"><CardContent className="p-6"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#e8f1e8] text-[#2d6d4a]"><Icon className="h-5 w-5"/></div><h2 className="mt-5 text-lg font-semibold text-[#173e2e]">{title as string}</h2><p className="mt-2 text-sm leading-6 text-[#728278]">{desc as string}</p></CardContent></Card>)}</section>
    <section className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e16d32]">Exemplo guiado</p><h2 className="mt-2 text-3xl font-semibold tracking-tight text-[#173e2e]">Assim a operação aparece dentro da plataforma</h2></div><div className="grid gap-6 lg:grid-cols-2"><Card className="border-[#dce7dc]"><CardHeader><CardTitle className="flex items-center gap-2 text-xl"><Trees className="h-5 w-5 text-[#36734e]"/> Propriedade “Vale Verde”</CardTitle><p className="text-xs font-medium text-[#e16d32]">{example}</p></CardHeader><CardContent><MiniChrome><div className="grid grid-cols-[1.1fr_.9fr] gap-3 p-4"><div className="relative min-h-[190px] overflow-hidden rounded-xl bg-[#dfead9] [background-image:repeating-radial-gradient(ellipse_at_20%_70%,transparent_0,transparent_19px,rgba(53,105,72,.25)_20px,transparent_21px,transparent_39px)]"><div className="absolute left-[18%] top-[22%] h-24 w-36 rotate-[-12deg] rounded-[40%] border-2 border-[#e16d32] bg-[#e16d32]/15"/><div className="absolute left-8 top-8 rounded bg-white/80 px-2 py-1 font-mono text-[9px] text-[#315c43]">T-04 · PINUS</div><div className="absolute bottom-3 right-3 rounded bg-[#123b2c] px-2 py-1 font-mono text-[9px] text-white">4,82 ha</div></div><div className="space-y-2"><div className="rounded-xl bg-white p-3"><p className="text-[9px] uppercase tracking-wider text-[#8a9a8d]">Talhões ativos</p><p className="mt-1 text-2xl font-semibold text-[#173e2e]">08</p></div><div className="rounded-xl bg-white p-3"><p className="text-[9px] uppercase tracking-wider text-[#8a9a8d]">Ciclo médio</p><p className="mt-1 text-sm font-semibold text-[#173e2e]">12,4 anos</p></div><div className="rounded-xl bg-[#fff2e9] p-3"><p className="text-[9px] uppercase tracking-wider text-[#bc6840]">Atenção</p><p className="mt-1 text-xs font-semibold text-[#934522]">1 vistoria pendente</p></div></div></div></MiniChrome><p className="mt-4 text-sm leading-6 text-[#718177]">No cadastro da propriedade, cada talhão recebe espécie, área, ciclo, coordenadas e documentos relacionados.</p></CardContent></Card>
    <Card className="border-[#dce7dc]"><CardHeader><CardTitle className="flex items-center gap-2 text-xl"><WalletCards className="h-5 w-5 text-[#36734e]"/> Visão do mês</CardTitle><p className="text-xs font-medium text-[#e16d32]">{example}</p></CardHeader><CardContent><MiniChrome><div className="grid grid-cols-2 gap-3 p-4"><div className="col-span-2 rounded-xl bg-[#123b2c] p-4 text-white"><p className="text-[9px] uppercase tracking-wider text-white/55">Caixa realizado</p><p className="mt-1 text-3xl font-semibold">R$ 42.680</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[72%] rounded-full bg-[#f08a4e]"/></div></div><div className="rounded-xl bg-white p-3"><p className="text-[9px] uppercase tracking-wider text-[#8a9a8d]">Recebido</p><p className="mt-1 text-lg font-semibold text-[#2d6d4a]">R$ 68.400</p></div><div className="rounded-xl bg-white p-3"><p className="text-[9px] uppercase tracking-wider text-[#8a9a8d]">Despesas pagas</p><p className="mt-1 text-lg font-semibold text-[#a35b39]">R$ 25.720</p></div><div className="col-span-2 rounded-xl border border-[#e4ece3] bg-white p-3"><div className="flex items-center justify-between"><p className="text-[9px] uppercase tracking-wider text-[#8a9a8d]">Últimos lançamentos</p><ReceiptText className="h-4 w-4 text-[#8ba18f]"/></div><div className="mt-3 space-y-2 text-xs"><div className="flex justify-between"><span className="text-[#61746a]">Ticket #TK-104 · pinus</span><b className="text-[#2d6d4a]">Conferido</b></div><div className="flex justify-between"><span className="text-[#61746a]">Contrato CV-08 · parcela 2/4</span><b className="text-[#e16d32]">A receber</b></div></div></div></div></MiniChrome><p className="mt-4 text-sm leading-6 text-[#718177]">O painel junta os registros aprovados e deixa claro o que já virou caixa e o que ainda está pendente.</p></CardContent></Card></div></section>
    <section className="grid gap-5 md:grid-cols-2"><Card className="border-[#dce7dc]"><CardContent className="p-6"><div className="flex items-center gap-3"><FileText className="h-5 w-5 text-[#e16d32]"/><h3 className="font-semibold text-[#173e2e]">Dica para começar</h3></div><p className="mt-3 text-sm leading-6 text-[#718177]">Cadastre primeiro uma propriedade, depois seus talhões e só então lance tickets e despesas. Assim os relatórios já nascem organizados.</p></CardContent></Card><Card className="border-[#dce7dc]"><CardContent className="p-6"><div className="flex items-center gap-3"><CheckCircle2 className="h-5 w-5 text-[#36734e]"/><h3 className="font-semibold text-[#173e2e]">Próximo passo</h3></div><p className="mt-3 text-sm leading-6 text-[#718177]">Quando estiver pronto, saia do exemplo e vá para a sua operação real.</p><Button className="mt-4 bg-[#123b2c] text-white hover:bg-[#1d5940]" onClick={() => setLocation("/talhoes")}>Abrir meus talhões <ArrowRight className="ml-2 h-4 w-4"/></Button></CardContent></Card></section>
  </div>;
}
