import { AlertTriangle, Loader2 } from "lucide-react";
import * as React from "react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { deletionNameMatches, deletionStageAfter, type DeletionStage } from "@/lib/territorySafety";

export function PropertyDeletionDialog({ open, propertyName, pending, onCancel, onConfirm }: { open: boolean; propertyName: string; pending: boolean; onCancel: () => void; onConfirm: (confirmationName: string) => void }) {
  const [stage, setStage] = useState<DeletionStage>("confirm");
  const [enteredName, setEnteredName] = useState("");
  useEffect(() => { if (open) { setStage("confirm"); setEnteredName(""); } }, [open, propertyName]);
  if (!open) return null;
  const cancel = () => { setStage(deletionStageAfter("cancel")); setEnteredName(""); onCancel(); };
  const matches = deletionNameMatches(propertyName, enteredName);
  return <div className="fixed inset-0 z-[60] flex items-end justify-center bg-[#10281d]/45 p-0 backdrop-blur-[2px] sm:items-center sm:p-5"><div role="dialog" aria-modal="true" aria-labelledby="delete-area-title" className="w-full max-w-lg overflow-hidden rounded-t-[1.8rem] bg-[#fdf8f7] shadow-2xl sm:rounded-[1.8rem]">{stage === "confirm" ? <div className="p-6 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-red-700">Confirmação necessária</p><h2 id="delete-area-title" className="mt-2 text-2xl font-semibold text-[#4b1f1c]">Excluir esta área?</h2><p className="mt-4 text-sm leading-6 text-[#6e4b47]">Tem certeza que deseja excluir <strong>{propertyName}</strong>? Na próxima etapa, você verá o aviso de exclusão permanente.</p><div className="mt-7 flex justify-end gap-3"><Button type="button" variant="outline" onClick={cancel}>Cancelar</Button><Button type="button" data-testid="advance-delete" onClick={() => setStage(deletionStageAfter("advance"))} className="bg-red-700 text-white hover:bg-red-800">Continuar</Button></div></div> : <div className="p-6 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-red-700">Zona de perigo</p><h2 id="delete-area-title" className="mt-2 text-2xl font-semibold text-[#4b1f1c]">Atenção: exclusão permanente</h2><div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm leading-6 text-red-900"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-red-700" /><p><strong>Esta ação não pode ser desfeita.</strong> A área, seus talhões, contratos, tickets, caixa, arquivos, vistorias e ocorrências vinculados serão apagados.</p></div></div><label className="mt-5 block text-xs font-semibold text-[#5d3733]">Digite “{propertyName}” para confirmar<input aria-label="Nome exato da área" value={enteredName} onChange={event => setEnteredName(event.target.value)} className="mt-1.5 h-11 w-full rounded-xl border border-red-200 bg-white px-3 text-sm text-[#4b1f1c] outline-none focus:border-red-500 focus:ring-4 focus:ring-red-100" autoComplete="off" /></label><div className="mt-7 flex justify-end gap-3"><Button type="button" variant="outline" onClick={cancel} disabled={pending}>Cancelar</Button><Button type="button" data-testid="confirm-delete" disabled={!matches || pending} onClick={() => onConfirm(enteredName)} className="bg-red-700 text-white hover:bg-red-800">{pending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Confirmar exclusão</Button></div></div>}</div></div>;
}
